on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ferranbt/github-action-suave@v2.2
        with:
          who-to-greet: "Mona the Octocat"
      - name: Which suave-geth
        run: suave version
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
