on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Install suave-geth
        uses: flashbots/suave-toolchain@v0.1

      - name: Which suave-geth
        run: suave-geth version
