on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ferranbt/github-action-suave@v2.6
        with:
          who-to-greet: "Mona the Octocat"
      - name: Which suave-geth
        run: suave-geth version
